name: Diceware CI

on: [push]
  push:
    paths:
      - 'home-consumer/**'
jobs:
  job1:
    name: Create package
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Package
        run: sbt universal:packageBin
