name: Home Consumer

on:
  push:
    paths:
      - 'consumer/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Package
        run: sbt universal:packageBin
        working-directory: ./consumer
      - uses: actions/upload-artifact@v1
        with:
          name: home-consumer
          path: ./consumer/target/universal/home-consumer-0.2.0-SNAPSHOT.zip
